name: Publish API To Docker

on:
  push:
    branches:
    - master

jobs:
  test_and_publish:
    name: Test And Publish To Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Tests
      uses: actions-hub/docker@master
      with:
        args: build --file docker/test/Dockerfile .
    - name: Docker Login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build Docker Image
      uses: actions-hub/docker@master
      with:
        args: build --rm --tag fisenkodv/dictum:api-latest --file docker/api/Dockerfile .
    - name: Publish To Docker Hub
      uses: actions-hub/docker@master
      with:
        args: push fisenkodv/dictum:api-latest
