name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
     steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build --rm --file docker/test/Dockerfile .

  build:
    runs-on: ubuntu-latest
     steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build --rm --tag fisenkodv/dictum:$(date +%s) --file docker/api/Dockerfile .
