name: Build and Publish

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Tests
      uses: actions/docker/cli@master
      with:
        args: build --file docker/test/Dockerfile .
  publish:
    name: Run Tests
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build Docker Image
      uses: actions/docker/cli@master
      with:
        args: build --rm --tag fisenkodv/dictum:latest --file docker/api/Dockerfile
          .
    - name: Publish To Docker Hub
      uses: actions/docker/cli@master
      with:
        args: push fisenkodv/dictum:latest
