name: Publish UI To Docker

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish To Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build Docker Image
      uses: actions-hub/docker@master
      with:
        args: build --rm --tag fisenkodv/dictum:ui-latest --file docker/ui/Dockerfile .
    - name: Publish To Docker Hub
      uses: actions-hub/docker@master
      with:
        args: push fisenkodv/dictum:ui-latest
